name: notes_2025
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dart_quill_delta: ^10.8.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_quill: ^11.5.0
  flutter_quill_extensions: ^11.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  modal_progress_hud_nsn: ^0.5.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  analyzer: 6.4.1
flutter:
  uses-material-design: true
flutter_icons:
  android: true
  ios: true
  image_path: "assets/Notes2.png"